server:
  port: 8080

spring:
  security:
    user:
      name: ${WEBSOCKET_USER:admin}
      password: ${WEBSOCKET_PASSWORD:changeme}

  application:
    name: chat

  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    driver-class-name: org.postgresql.Driver
    username: root 
    password: Password!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  # kafka:
  #   bootstrap-servers: localhost:9092
  #   consumer:
  #     group-id: chat-group
  #     auto-offset-reset: earliest
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: yourSecretKey
  expiration: 86400000 # 24 hours in milliseconds

websocket:
  endpoint: /ws
  destination-prefix: /app
  topic-prefix: /topic

